name: Super Automation

on:
  schedule:
    - cron: '0 0 1,4,7,10,13,16,19,22,25,28 * *'  # Every 3 days at 00:00 UTC
  workflow_dispatch:  # Allow manual run too

permissions:
  contents: read

jobs:
  request-super:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Super Request
        run: |
          echo "🚀 Requesting Super..."
          RESPONSE=$(curl --ssl-no-revoke -s -X POST https://api.duolingopro.net/request \
            -H "Authorization: Bearer ${{ secrets.DUOLINGO_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"type": "super"}')
          echo "📝 Response from server:"
          echo "$RESPONSE"
