name: XP Automation

on:
  schedule:
    - cron: '5 */4 * * *'  # Runs every 4 hours at minute 5 (UTC)
  workflow_dispatch:        # Allows manual triggering

permissions:
  contents: write  # Changed from 'read' to 'write' to commit dashboard image

jobs:
  send-xp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: |
          npm install puppeteer

      - name: Generate Dashboard GIF
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({
              headless: true,
              args: ['--no-sandbox', '--disable-setuid-sandbox']
            });
            const page = await browser.newPage();
            await page.setViewport({width: 800, height: 400});
            await page.goto('file://' + process.cwd() + '/dashboard.html', {waitUntil: 'networkidle2'});
            
            // Record multiple frames for GIF
            const frames = [];
            for(let i = 0; i < 30; i++) { // 30 frames = ~3 seconds at 10fps
              await new Promise(resolve => setTimeout(resolve, 100)); // 100ms between frames
              const screenshot = await page.screenshot({type: 'png'});
              frames.push(screenshot);
            }
            
            // Save as static PNG for now (will add GIF conversion)
            await page.screenshot({path: 'dashboard.png', type: 'png'});
            await browser.close();
            console.log('Dashboard frames captured!');
          })();
          "

      - name: Run XP request
        run: |
          echo "📤 Sending XP request..."
          RESPONSE=$(curl --ssl-no-revoke -s -X POST https://api.duolingopro.net/request \
            -H "Authorization: Bearer ${{ secrets.DUOLINGO_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"gain_type": "xp", "amount": 30000}')
          echo "📨 Response from server:"
          echo "$RESPONSE"

      - name: Commit and push dashboard image
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dashboard.png
          git diff --staged --quiet || git commit -m "Update dashboard image [automated]"
          git push
